# Change these first
owner: andrewdavies-net # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: sdc
    url: $SDC
  - name: nh
    url: $NH
  - name: sso
    url: $SSO
  - name: jellyfin
    url: $JELLYFIN
  - name: nhcam
    url: $NHIPCAM
  - name: pass
    url: $PASS
  - name: plex
    url: $plex
  - name: plexd
    url: $PLEXD
  - name: requests
    url: $REQUESTS

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.andrewdavies.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Services Uptime"
  introTitle: "Uptime of services"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
